### ISSUE TITLE
core.norg.concealer is deprecated

### ISSUE THREAD

**Issue by sergiornelas** [max397574/neorg-contexts#1]
Hello, recently neorg made an update and `core.norg.concealer` is deprecated.
Instead use `core.concealer`. (line 44 in the code):
https://github.com/max397574/neorg-contexts/blob/master/lua/neorg/modules/external/context/module.lua

Besides, that module does not seem to set module.setup().requires correctly (line 15) since it should make concealer a dependency as well.

**Comment by pysan3** [comment]
> Besides, that module does not seem to set module.setup().requires correctly (line 15) since it should make concealer a dependency as well.

Hi @max397574, you forgot to update the dependencies. Or is there a reason you don't add concealer as a dependency?

**Comment by max397574** [comment]
🤔 for me it works like this
but I'll do that as well then

edit: done

**Comment by pysan3** [comment]
It sure does work if nothing is going wrong but it's that if the check is in `requires`, it checks the dependencies on startup, meaning that the error message is very clear that it could not find that dependency.

But if you randomly require it inside the module, that dependency error happens at runtime and the error message will become very hard to diagnose (which was literally what happened this time).

Thanks for the fix ;)
